// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type PostStatus string

const (
	PostStatusDraft     PostStatus = "draft"
	PostStatusPublished PostStatus = "published"
	PostStatusArchived  PostStatus = "archived"
)

func (e *PostStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PostStatus(s)
	case string:
		*e = PostStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PostStatus: %T", src)
	}
	return nil
}

type NullPostStatus struct {
	PostStatus PostStatus `json:"post_status"`
	Valid      bool       `json:"valid"` // Valid is true if PostStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPostStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PostStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PostStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPostStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PostStatus), nil
}

type Comment struct {
	ID        pgtype.UUID        `json:"id"`
	PostID    pgtype.UUID        `json:"post_id"`
	AuthorID  pgtype.UUID        `json:"author_id"`
	Content   string             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Post struct {
	ID         pgtype.UUID        `json:"id"`
	AuthorID   pgtype.UUID        `json:"author_id"`
	Title      string             `json:"title"`
	Slug       string             `json:"slug"`
	Content    string             `json:"content"`
	Excerpt    pgtype.Text        `json:"excerpt"`
	Status     PostStatus         `json:"status"`
	Categories []string           `json:"categories"`
	Tags       []string           `json:"tags"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	PasswordSalt string             `json:"password_salt"`
	FirstName    string             `json:"first_name"`
	LastName     string             `json:"last_name"`
	AvatarUrl    pgtype.Text        `json:"avatar_url"`
	Bio          pgtype.Text        `json:"bio"`
	RoleID       pgtype.UUID        `json:"role_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type UserRole struct {
	ID     pgtype.UUID `json:"id"`
	Slug   string      `json:"slug"`
	Scopes []string    `json:"scopes"`
}
