// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countComments = `-- name: CountComments :one
SELECT count(*) FROM comments WHERE post_id = $1
`

func (q *Queries) CountComments(ctx context.Context, postID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countComments, postID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPosts = `-- name: CountPosts :one
SELECT count(*)
FROM posts
WHERE ($1::post_status IS NULL OR posts.status = $1)
  AND ($2::text IS NULL OR $2 = ANY(posts.tags))
  AND ($3::text IS NULL OR $3 = ANY(posts.categories))
`

type CountPostsParams struct {
	Status   NullPostStatus `json:"status"`
	Tag      pgtype.Text    `json:"tag"`
	Category pgtype.Text    `json:"category"`
}

func (q *Queries) CountPosts(ctx context.Context, arg CountPostsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPosts, arg.Status, arg.Tag, arg.Category)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createComment = `-- name: CreateComment :one

INSERT INTO comments (post_id, author_id, content)
VALUES ($1, $2, $3)
RETURNING id, post_id, author_id, content, created_at, updated_at
`

type CreateCommentParams struct {
	PostID   pgtype.UUID `json:"post_id"`
	AuthorID pgtype.UUID `json:"author_id"`
	Content  string      `json:"content"`
}

// Comments --------------------------------------------------------------------
func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, createComment, arg.PostID, arg.AuthorID, arg.Content)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.AuthorID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPost = `-- name: CreatePost :one

INSERT INTO posts (
  author_id, title, slug, content, excerpt, status, categories, tags
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, author_id, title, slug, content, excerpt, status, categories, tags, created_at, updated_at
`

type CreatePostParams struct {
	AuthorID   pgtype.UUID `json:"author_id"`
	Title      string      `json:"title"`
	Slug       string      `json:"slug"`
	Content    string      `json:"content"`
	Excerpt    pgtype.Text `json:"excerpt"`
	Status     PostStatus  `json:"status"`
	Categories []string    `json:"categories"`
	Tags       []string    `json:"tags"`
}

// Posts -----------------------------------------------------------------------
// comment_count is derived; dynamic API sort is not expressible in static SQL
// so ordering is fixed here and the handler ignores the `sort` query param.
func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, createPost,
		arg.AuthorID,
		arg.Title,
		arg.Slug,
		arg.Content,
		arg.Excerpt,
		arg.Status,
		arg.Categories,
		arg.Tags,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Title,
		&i.Slug,
		&i.Content,
		&i.Excerpt,
		&i.Status,
		&i.Categories,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one

INSERT INTO users (
  email, password_hash, password_salt, first_name, last_name, avatar_url, bio, role_id
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, email, password_hash, password_salt, first_name, last_name, avatar_url, bio, role_id, created_at, updated_at
`

type CreateUserParams struct {
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
	PasswordSalt string      `json:"password_salt"`
	FirstName    string      `json:"first_name"`
	LastName     string      `json:"last_name"`
	AvatarUrl    pgtype.Text `json:"avatar_url"`
	Bio          pgtype.Text `json:"bio"`
	RoleID       pgtype.UUID `json:"role_id"`
}

// Users -----------------------------------------------------------------------
// SELECTs embed the role so callers get scopes without a second query.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.PasswordSalt,
		arg.FirstName,
		arg.LastName,
		arg.AvatarUrl,
		arg.Bio,
		arg.RoleID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.PasswordSalt,
		&i.FirstName,
		&i.LastName,
		&i.AvatarUrl,
		&i.Bio,
		&i.RoleID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteComment = `-- name: DeleteComment :exec
DELETE FROM comments WHERE id = $1
`

func (q *Queries) DeleteComment(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteComment, id)
	return err
}

const deletePost = `-- name: DeletePost :exec
DELETE FROM posts WHERE id = $1
`

func (q *Queries) DeletePost(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePost, id)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getComment = `-- name: GetComment :one
SELECT id, post_id, author_id, content, created_at, updated_at FROM comments WHERE id = $1
`

func (q *Queries) GetComment(ctx context.Context, id pgtype.UUID) (Comment, error) {
	row := q.db.QueryRow(ctx, getComment, id)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.AuthorID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPost = `-- name: GetPost :one
SELECT
  posts.id, posts.author_id, posts.title, posts.slug, posts.content, posts.excerpt, posts.status, posts.categories, posts.tags, posts.created_at, posts.updated_at,
  (SELECT count(*) FROM comments c WHERE c.post_id = posts.id) AS comment_count
FROM posts
WHERE posts.id = $1
`

type GetPostRow struct {
	Post         Post  `json:"post"`
	CommentCount int64 `json:"comment_count"`
}

func (q *Queries) GetPost(ctx context.Context, id pgtype.UUID) (GetPostRow, error) {
	row := q.db.QueryRow(ctx, getPost, id)
	var i GetPostRow
	err := row.Scan(
		&i.Post.ID,
		&i.Post.AuthorID,
		&i.Post.Title,
		&i.Post.Slug,
		&i.Post.Content,
		&i.Post.Excerpt,
		&i.Post.Status,
		&i.Post.Categories,
		&i.Post.Tags,
		&i.Post.CreatedAt,
		&i.Post.UpdatedAt,
		&i.CommentCount,
	)
	return i, err
}

const getRole = `-- name: GetRole :one

SELECT id, slug, scopes FROM user_roles WHERE id = $1
`

// Roles -----------------------------------------------------------------------
func (q *Queries) GetRole(ctx context.Context, id pgtype.UUID) (UserRole, error) {
	row := q.db.QueryRow(ctx, getRole, id)
	var i UserRole
	err := row.Scan(&i.ID, &i.Slug, &i.Scopes)
	return i, err
}

const getRoleBySlug = `-- name: GetRoleBySlug :one
SELECT id, slug, scopes FROM user_roles WHERE slug = $1
`

func (q *Queries) GetRoleBySlug(ctx context.Context, slug string) (UserRole, error) {
	row := q.db.QueryRow(ctx, getRoleBySlug, slug)
	var i UserRole
	err := row.Scan(&i.ID, &i.Slug, &i.Scopes)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT users.id, users.email, users.password_hash, users.password_salt, users.first_name, users.last_name, users.avatar_url, users.bio, users.role_id, users.created_at, users.updated_at, user_roles.id, user_roles.slug, user_roles.scopes
FROM users
JOIN user_roles ON user_roles.id = users.role_id
WHERE users.id = $1
`

type GetUserRow struct {
	User     User     `json:"user"`
	UserRole UserRole `json:"user_role"`
}

func (q *Queries) GetUser(ctx context.Context, id pgtype.UUID) (GetUserRow, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i GetUserRow
	err := row.Scan(
		&i.User.ID,
		&i.User.Email,
		&i.User.PasswordHash,
		&i.User.PasswordSalt,
		&i.User.FirstName,
		&i.User.LastName,
		&i.User.AvatarUrl,
		&i.User.Bio,
		&i.User.RoleID,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
		&i.UserRole.ID,
		&i.UserRole.Slug,
		&i.UserRole.Scopes,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT users.id, users.email, users.password_hash, users.password_salt, users.first_name, users.last_name, users.avatar_url, users.bio, users.role_id, users.created_at, users.updated_at, user_roles.id, user_roles.slug, user_roles.scopes
FROM users
JOIN user_roles ON user_roles.id = users.role_id
WHERE users.email = $1
`

type GetUserByEmailRow struct {
	User     User     `json:"user"`
	UserRole UserRole `json:"user_role"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.User.ID,
		&i.User.Email,
		&i.User.PasswordHash,
		&i.User.PasswordSalt,
		&i.User.FirstName,
		&i.User.LastName,
		&i.User.AvatarUrl,
		&i.User.Bio,
		&i.User.RoleID,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
		&i.UserRole.ID,
		&i.UserRole.Slug,
		&i.UserRole.Scopes,
	)
	return i, err
}

const listComments = `-- name: ListComments :many
SELECT id, post_id, author_id, content, created_at, updated_at FROM comments
WHERE post_id = $1
ORDER BY created_at ASC
LIMIT $2 OFFSET $3
`

type ListCommentsParams struct {
	PostID pgtype.UUID `json:"post_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListComments(ctx context.Context, arg ListCommentsParams) ([]Comment, error) {
	rows, err := q.db.Query(ctx, listComments, arg.PostID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Comment
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.AuthorID,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPosts = `-- name: ListPosts :many
SELECT
  posts.id, posts.author_id, posts.title, posts.slug, posts.content, posts.excerpt, posts.status, posts.categories, posts.tags, posts.created_at, posts.updated_at,
  (SELECT count(*) FROM comments c WHERE c.post_id = posts.id) AS comment_count
FROM posts
WHERE ($1::post_status IS NULL OR posts.status = $1)
  AND ($2::text IS NULL OR $2 = ANY(posts.tags))
  AND ($3::text IS NULL OR $3 = ANY(posts.categories))
ORDER BY posts.created_at DESC
LIMIT $5 OFFSET $4
`

type ListPostsParams struct {
	Status   NullPostStatus `json:"status"`
	Tag      pgtype.Text    `json:"tag"`
	Category pgtype.Text    `json:"category"`
	Offset   int32          `json:"offset"`
	Limit    int32          `json:"limit"`
}

type ListPostsRow struct {
	Post         Post  `json:"post"`
	CommentCount int64 `json:"comment_count"`
}

func (q *Queries) ListPosts(ctx context.Context, arg ListPostsParams) ([]ListPostsRow, error) {
	rows, err := q.db.Query(ctx, listPosts,
		arg.Status,
		arg.Tag,
		arg.Category,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPostsRow
	for rows.Next() {
		var i ListPostsRow
		if err := rows.Scan(
			&i.Post.ID,
			&i.Post.AuthorID,
			&i.Post.Title,
			&i.Post.Slug,
			&i.Post.Content,
			&i.Post.Excerpt,
			&i.Post.Status,
			&i.Post.Categories,
			&i.Post.Tags,
			&i.Post.CreatedAt,
			&i.Post.UpdatedAt,
			&i.CommentCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoles = `-- name: ListRoles :many
SELECT id, slug, scopes FROM user_roles ORDER BY slug
`

func (q *Queries) ListRoles(ctx context.Context) ([]UserRole, error) {
	rows, err := q.db.Query(ctx, listRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserRole
	for rows.Next() {
		var i UserRole
		if err := rows.Scan(&i.ID, &i.Slug, &i.Scopes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT users.id, users.email, users.password_hash, users.password_salt, users.first_name, users.last_name, users.avatar_url, users.bio, users.role_id, users.created_at, users.updated_at, user_roles.id, user_roles.slug, user_roles.scopes
FROM users
JOIN user_roles ON user_roles.id = users.role_id
ORDER BY users.created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListUsersRow struct {
	User     User     `json:"user"`
	UserRole UserRole `json:"user_role"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.User.ID,
			&i.User.Email,
			&i.User.PasswordHash,
			&i.User.PasswordSalt,
			&i.User.FirstName,
			&i.User.LastName,
			&i.User.AvatarUrl,
			&i.User.Bio,
			&i.User.RoleID,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
			&i.UserRole.ID,
			&i.UserRole.Slug,
			&i.UserRole.Scopes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replacePost = `-- name: ReplacePost :one
UPDATE posts SET
  title      = $2,
  slug       = $3,
  content    = $4,
  excerpt    = $5,
  status     = $6,
  categories = $7,
  tags       = $8,
  updated_at = now()
WHERE id = $1
RETURNING id, author_id, title, slug, content, excerpt, status, categories, tags, created_at, updated_at
`

type ReplacePostParams struct {
	ID         pgtype.UUID `json:"id"`
	Title      string      `json:"title"`
	Slug       string      `json:"slug"`
	Content    string      `json:"content"`
	Excerpt    pgtype.Text `json:"excerpt"`
	Status     PostStatus  `json:"status"`
	Categories []string    `json:"categories"`
	Tags       []string    `json:"tags"`
}

func (q *Queries) ReplacePost(ctx context.Context, arg ReplacePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, replacePost,
		arg.ID,
		arg.Title,
		arg.Slug,
		arg.Content,
		arg.Excerpt,
		arg.Status,
		arg.Categories,
		arg.Tags,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Title,
		&i.Slug,
		&i.Content,
		&i.Excerpt,
		&i.Status,
		&i.Categories,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const replaceUser = `-- name: ReplaceUser :one
UPDATE users SET
  email         = $2,
  password_hash = $3,
  password_salt = $4,
  first_name    = $5,
  last_name     = $6,
  avatar_url    = $7,
  bio           = $8,
  role_id       = $9,
  updated_at    = now()
WHERE id = $1
RETURNING id, email, password_hash, password_salt, first_name, last_name, avatar_url, bio, role_id, created_at, updated_at
`

type ReplaceUserParams struct {
	ID           pgtype.UUID `json:"id"`
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
	PasswordSalt string      `json:"password_salt"`
	FirstName    string      `json:"first_name"`
	LastName     string      `json:"last_name"`
	AvatarUrl    pgtype.Text `json:"avatar_url"`
	Bio          pgtype.Text `json:"bio"`
	RoleID       pgtype.UUID `json:"role_id"`
}

func (q *Queries) ReplaceUser(ctx context.Context, arg ReplaceUserParams) (User, error) {
	row := q.db.QueryRow(ctx, replaceUser,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.PasswordSalt,
		arg.FirstName,
		arg.LastName,
		arg.AvatarUrl,
		arg.Bio,
		arg.RoleID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.PasswordSalt,
		&i.FirstName,
		&i.LastName,
		&i.AvatarUrl,
		&i.Bio,
		&i.RoleID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateComment = `-- name: UpdateComment :one
UPDATE comments SET
  content    = $2,
  updated_at = now()
WHERE id = $1
RETURNING id, post_id, author_id, content, created_at, updated_at
`

type UpdateCommentParams struct {
	ID      pgtype.UUID `json:"id"`
	Content string      `json:"content"`
}

func (q *Queries) UpdateComment(ctx context.Context, arg UpdateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, updateComment, arg.ID, arg.Content)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.AuthorID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET
  email         = COALESCE($1, email),
  password_hash = COALESCE($2, password_hash),
  password_salt = COALESCE($3, password_salt),
  first_name    = COALESCE($4, first_name),
  last_name     = COALESCE($5, last_name),
  avatar_url    = COALESCE($6, avatar_url),
  bio           = COALESCE($7, bio),
  role_id       = COALESCE($8, role_id),
  updated_at    = now()
WHERE id = $9
RETURNING id, email, password_hash, password_salt, first_name, last_name, avatar_url, bio, role_id, created_at, updated_at
`

type UpdateUserParams struct {
	Email        pgtype.Text `json:"email"`
	PasswordHash pgtype.Text `json:"password_hash"`
	PasswordSalt pgtype.Text `json:"password_salt"`
	FirstName    pgtype.Text `json:"first_name"`
	LastName     pgtype.Text `json:"last_name"`
	AvatarUrl    pgtype.Text `json:"avatar_url"`
	Bio          pgtype.Text `json:"bio"`
	RoleID       pgtype.UUID `json:"role_id"`
	ID           pgtype.UUID `json:"id"`
}

// Partial update: NULL args leave the column unchanged.
func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Email,
		arg.PasswordHash,
		arg.PasswordSalt,
		arg.FirstName,
		arg.LastName,
		arg.AvatarUrl,
		arg.Bio,
		arg.RoleID,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.PasswordSalt,
		&i.FirstName,
		&i.LastName,
		&i.AvatarUrl,
		&i.Bio,
		&i.RoleID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
