apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: postgres

resources:
  - Namespace-postgres.yaml
  - ServiceAccount-postgres.yaml
  - StatefulSet-postgres.yaml
  - Service-postgres.yaml
  - PodDisruptionBudget-postgres.yaml

images:
  - name: postgres
    newName: postgres
    newTag: "18"
