apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gateway
spec:
  gatewayClassName: kgateway
  listeners:
    - name: api-demo-localhost-http
      hostname: api.demo.localhost
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All
    - name: auth-demo-localhost-http
      hostname: auth.demo.localhost
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All
