apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-policy-agent
  labels:
    app.kubernetes.io/name: open-policy-agent
    app.kubernetes.io/part-of: infra
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/language: go
    app.kubernetes.io/component: api
    app.kubernetes.io/instance: infra-open-policy-agent-api
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: infra-open-policy-agent-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: open-policy-agent
        app.kubernetes.io/part-of: infra
        app.kubernetes.io/managed-by: kustomize
        app.kubernetes.io/language: go
        app.kubernetes.io/component: api
        app.kubernetes.io/instance: infra-open-policy-agent-api
    spec:
      serviceAccountName: open-policy-agent
      containers:
        - name: open-policy-agent
          image: open-policy-agent
          imagePullPolicy: Always
          args:
            - run
            - "--server"
            - "--addr=0.0.0.0:8181"
            - "--diagnostic-addr=0.0.0.0:8282"
            - "--log-format=json"
            - "--config-file=/config/opa-envoy.yaml"
            - "--watch"
            - /policies/authz/platform.rego
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi
          env:
            - name: RS256_CERT
              valueFrom:
                configMapKeyRef:
                  name: opa-envoy-config
                  key: rs256.pem
          livenessProbe:
            httpGet:
              path: /health?plugins
              port: diag
            initialDelaySeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health?plugins
              port: diag
            initialDelaySeconds: 5
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
          ports:
            - containerPort: 8181
              name: http
            - containerPort: 9191
              name: grpc
            - containerPort: 8282
              name: diag
          volumeMounts:
            - name: policies
              mountPath: /policies/authz
              readOnly: true
            - name: config
              mountPath: /config
              readOnly: true
      volumes:
        - name: policies
          configMap:
            name: opa-policies
        - name: config
          configMap:
            name: opa-envoy-config
      restartPolicy: Always
