apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: open-policy-agent

resources:
  - Namespace-open-policy-agent.yaml
  - ServiceAccount-open-policy-agent.yaml
  - Deployment-open-policy-agent.yaml
  - Service-open-policy-agent.yaml
  - PodDisruptionBudget-open-policy-agent.yaml
  - HorizontalPodAutoscaler-open-policy-agent.yaml
  - ReferenceGrant-opa-envoy.yaml

configMapGenerator:
  - name: opa-policies
    files:
      - ./policies/envoy/authz/platform.rego
  - name: opa-envoy-config
    files:
      - ./config/opa-envoy.yaml
      - ./config/rs256.pem

images:
  - name: open-policy-agent
    newName: openpolicyagent/opa
    newTag: 1.18.2-envoy-static
