apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: opa-envoy-extauth
spec:
  from:
    - group: gateway.kgateway.dev
      kind: GatewayExtension
      namespace: gateway
  to:
    - group: ""
      kind: Service
      name: open-policy-agent
