apiVersion: v1
kind: ServiceAccount
metadata:
  name: open-policy-agent
  labels:
    app.kubernetes.io/name: open-policy-agent
    app.kubernetes.io/part-of: infra
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/language: go
    app.kubernetes.io/component: api
    app.kubernetes.io/instance: infra-open-policy-agent-api
