apiVersion: v1
kind: Service
metadata:
  name: open-policy-agent
  labels:
    app.kubernetes.io/name: open-policy-agent
    app.kubernetes.io/part-of: infra
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/language: go
    app.kubernetes.io/component: api
    app.kubernetes.io/instance: infra-open-policy-agent-api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: infra-open-policy-agent-api
  ports:
    - name: http
      port: 8181
      targetPort: 8181
    - name: grpc
      port: 9191
      targetPort: 9191
      appProtocol: kubernetes.io/h2c
    - name: diag
      port: 8282
      targetPort: 8282
