---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jsonplaceholder

resources:
  - Namespace-jsonplaceholder.yaml
  - Deployment-jsonplaceholder.yaml
  - HorizontalPodAutoscaler-jsonplaceholder.yaml
  - PodDisruptionBudget-jsonplaceholder.yaml
  - Service-jsonplaceholder.yaml
  - HTTPRoute-jsonplaceholder.yaml

images:
  - name: jsonplaceholder
    newName: svenwal/jsonplaceholder
    newTag: "1.1"
